(cl:in-package runtime_manager-msg)
(cl:export '(HEADER-VAL
          HEADER
          PARAM_FLAG-VAL
          PARAM_FLAG
          VELOCITY-VAL
          VELOCITY
          LOOKAHEAD_THRESHOLD-VAL
          LOOKAHEAD_THRESHOLD
          THRESHOLD_RATIO-VAL
          THRESHOLD_RATIO
          MINIMUM_LOOKAHEAD_THRESHOLD-VAL
          MINIMUM_LOOKAHEAD_THRESHOLD
          DISPLACEMENT_THRESHOLD-VAL
          DISPLACEMENT_THRESHOLD
          RELATIVE_ANGLE_THRESHOLD-VAL
          RELATIVE_ANGLE_THRESHOLD
))