// Generated by gencpp from file map_file/AreaClass.msg
// DO NOT EDIT!


#ifndef MAP_FILE_MESSAGE_AREACLASS_H
#define MAP_FILE_MESSAGE_AREACLASS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_file
{
template <class ContainerAllocator>
struct AreaClass_
{
  typedef AreaClass_<ContainerAllocator> Type;

  AreaClass_()
    : aid(0)
    , slid(0)
    , elid(0)  {
    }
  AreaClass_(const ContainerAllocator& _alloc)
    : aid(0)
    , slid(0)
    , elid(0)  {
  (void)_alloc;
    }



   typedef int32_t _aid_type;
  _aid_type aid;

   typedef int32_t _slid_type;
  _slid_type slid;

   typedef int32_t _elid_type;
  _elid_type elid;




  typedef boost::shared_ptr< ::map_file::AreaClass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_file::AreaClass_<ContainerAllocator> const> ConstPtr;

}; // struct AreaClass_

typedef ::map_file::AreaClass_<std::allocator<void> > AreaClass;

typedef boost::shared_ptr< ::map_file::AreaClass > AreaClassPtr;
typedef boost::shared_ptr< ::map_file::AreaClass const> AreaClassConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_file::AreaClass_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_file::AreaClass_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_file

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'map_file': ['/home/hj/catkin_ws/src/data/packages/map_file/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_file::AreaClass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_file::AreaClass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::AreaClass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::AreaClass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::AreaClass_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::AreaClass_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_file::AreaClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54e3c8d0cac454f97de72b3d7d888691";
  }

  static const char* value(const ::map_file::AreaClass_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54e3c8d0cac454f9ULL;
  static const uint64_t static_value2 = 0x7de72b3d7d888691ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_file::AreaClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_file/AreaClass";
  }

  static const char* value(const ::map_file::AreaClass_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_file::AreaClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 aid\n\
int32 slid\n\
int32 elid\n\
";
  }

  static const char* value(const ::map_file::AreaClass_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_file::AreaClass_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.aid);
      stream.next(m.slid);
      stream.next(m.elid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AreaClass_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_file::AreaClass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_file::AreaClass_<ContainerAllocator>& v)
  {
    s << indent << "aid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.aid);
    s << indent << "slid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.slid);
    s << indent << "elid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.elid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_FILE_MESSAGE_AREACLASS_H
