// Generated by gencpp from file map_file/BoxClass.msg
// DO NOT EDIT!


#ifndef MAP_FILE_MESSAGE_BOXCLASS_H
#define MAP_FILE_MESSAGE_BOXCLASS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_file
{
template <class ContainerAllocator>
struct BoxClass_
{
  typedef BoxClass_<ContainerAllocator> Type;

  BoxClass_()
    : bid(0)
    , pid1(0)
    , pid2(0)
    , pid3(0)
    , pid4(0)
    , height(0.0)  {
    }
  BoxClass_(const ContainerAllocator& _alloc)
    : bid(0)
    , pid1(0)
    , pid2(0)
    , pid3(0)
    , pid4(0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _bid_type;
  _bid_type bid;

   typedef int32_t _pid1_type;
  _pid1_type pid1;

   typedef int32_t _pid2_type;
  _pid2_type pid2;

   typedef int32_t _pid3_type;
  _pid3_type pid3;

   typedef int32_t _pid4_type;
  _pid4_type pid4;

   typedef double _height_type;
  _height_type height;




  typedef boost::shared_ptr< ::map_file::BoxClass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_file::BoxClass_<ContainerAllocator> const> ConstPtr;

}; // struct BoxClass_

typedef ::map_file::BoxClass_<std::allocator<void> > BoxClass;

typedef boost::shared_ptr< ::map_file::BoxClass > BoxClassPtr;
typedef boost::shared_ptr< ::map_file::BoxClass const> BoxClassConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_file::BoxClass_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_file::BoxClass_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_file

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'map_file': ['/home/hj/catkin_ws/src/data/packages/map_file/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_file::BoxClass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_file::BoxClass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::BoxClass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::BoxClass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::BoxClass_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::BoxClass_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_file::BoxClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "279dc10360643592a62c756918e5d27e";
  }

  static const char* value(const ::map_file::BoxClass_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x279dc10360643592ULL;
  static const uint64_t static_value2 = 0xa62c756918e5d27eULL;
};

template<class ContainerAllocator>
struct DataType< ::map_file::BoxClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_file/BoxClass";
  }

  static const char* value(const ::map_file::BoxClass_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_file::BoxClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 bid\n\
int32 pid1\n\
int32 pid2\n\
int32 pid3\n\
int32 pid4\n\
float64 height\n\
";
  }

  static const char* value(const ::map_file::BoxClass_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_file::BoxClass_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bid);
      stream.next(m.pid1);
      stream.next(m.pid2);
      stream.next(m.pid3);
      stream.next(m.pid4);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoxClass_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_file::BoxClass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_file::BoxClass_<ContainerAllocator>& v)
  {
    s << indent << "bid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bid);
    s << indent << "pid1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pid1);
    s << indent << "pid2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pid2);
    s << indent << "pid3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pid3);
    s << indent << "pid4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pid4);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_FILE_MESSAGE_BOXCLASS_H
