// Generated by gencpp from file map_file/LaneArray.msg
// DO NOT EDIT!


#ifndef MAP_FILE_MESSAGE_LANEARRAY_H
#define MAP_FILE_MESSAGE_LANEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <map_file/Lane.h>

namespace map_file
{
template <class ContainerAllocator>
struct LaneArray_
{
  typedef LaneArray_<ContainerAllocator> Type;

  LaneArray_()
    : header()
    , lanes()  {
    }
  LaneArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lanes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::map_file::Lane_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::map_file::Lane_<ContainerAllocator> >::other >  _lanes_type;
  _lanes_type lanes;




  typedef boost::shared_ptr< ::map_file::LaneArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_file::LaneArray_<ContainerAllocator> const> ConstPtr;

}; // struct LaneArray_

typedef ::map_file::LaneArray_<std::allocator<void> > LaneArray;

typedef boost::shared_ptr< ::map_file::LaneArray > LaneArrayPtr;
typedef boost::shared_ptr< ::map_file::LaneArray const> LaneArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_file::LaneArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_file::LaneArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_file

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'map_file': ['/home/hj/catkin_ws/src/data/packages/map_file/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_file::LaneArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_file::LaneArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::LaneArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::LaneArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::LaneArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::LaneArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_file::LaneArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef0bc3357116c3774aae9f96f704f7f7";
  }

  static const char* value(const ::map_file::LaneArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef0bc3357116c377ULL;
  static const uint64_t static_value2 = 0x4aae9f96f704f7f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_file::LaneArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_file/LaneArray";
  }

  static const char* value(const ::map_file::LaneArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_file::LaneArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Lane[] lanes\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: map_file/Lane\n\
int32 lnid\n\
int32 did\n\
int32 blid\n\
int32 flid\n\
int32 bnid\n\
int32 fnid\n\
int32 jct\n\
int32 blid2\n\
int32 blid3\n\
int32 blid4\n\
int32 flid2\n\
int32 flid3\n\
int32 flid4\n\
int32 clossid\n\
float64 span\n\
int32 lcnt\n\
int32 lno\n\
";
  }

  static const char* value(const ::map_file::LaneArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_file::LaneArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lanes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_file::LaneArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_file::LaneArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lanes[]" << std::endl;
    for (size_t i = 0; i < v.lanes.size(); ++i)
    {
      s << indent << "  lanes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::map_file::Lane_<ContainerAllocator> >::stream(s, indent + "    ", v.lanes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_FILE_MESSAGE_LANEARRAY_H
