// Generated by gencpp from file map_file/LineClass.msg
// DO NOT EDIT!


#ifndef MAP_FILE_MESSAGE_LINECLASS_H
#define MAP_FILE_MESSAGE_LINECLASS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_file
{
template <class ContainerAllocator>
struct LineClass_
{
  typedef LineClass_<ContainerAllocator> Type;

  LineClass_()
    : lid(0)
    , bpid(0)
    , fpid(0)
    , blid(0)
    , flid(0)  {
    }
  LineClass_(const ContainerAllocator& _alloc)
    : lid(0)
    , bpid(0)
    , fpid(0)
    , blid(0)
    , flid(0)  {
  (void)_alloc;
    }



   typedef int32_t _lid_type;
  _lid_type lid;

   typedef int32_t _bpid_type;
  _bpid_type bpid;

   typedef int32_t _fpid_type;
  _fpid_type fpid;

   typedef int32_t _blid_type;
  _blid_type blid;

   typedef int32_t _flid_type;
  _flid_type flid;




  typedef boost::shared_ptr< ::map_file::LineClass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_file::LineClass_<ContainerAllocator> const> ConstPtr;

}; // struct LineClass_

typedef ::map_file::LineClass_<std::allocator<void> > LineClass;

typedef boost::shared_ptr< ::map_file::LineClass > LineClassPtr;
typedef boost::shared_ptr< ::map_file::LineClass const> LineClassConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_file::LineClass_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_file::LineClass_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_file

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'map_file': ['/home/hj/catkin_ws/src/data/packages/map_file/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_file::LineClass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_file::LineClass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::LineClass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::LineClass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::LineClass_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::LineClass_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_file::LineClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f019727ac91c69fd42d5922bf464911";
  }

  static const char* value(const ::map_file::LineClass_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f019727ac91c69fULL;
  static const uint64_t static_value2 = 0xd42d5922bf464911ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_file::LineClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_file/LineClass";
  }

  static const char* value(const ::map_file::LineClass_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_file::LineClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 lid\n\
int32 bpid\n\
int32 fpid\n\
int32 blid\n\
int32 flid\n\
";
  }

  static const char* value(const ::map_file::LineClass_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_file::LineClass_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lid);
      stream.next(m.bpid);
      stream.next(m.fpid);
      stream.next(m.blid);
      stream.next(m.flid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineClass_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_file::LineClass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_file::LineClass_<ContainerAllocator>& v)
  {
    s << indent << "lid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lid);
    s << indent << "bpid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bpid);
    s << indent << "fpid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fpid);
    s << indent << "blid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.blid);
    s << indent << "flid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.flid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_FILE_MESSAGE_LINECLASS_H
