// Generated by gencpp from file map_file/RoadMark.msg
// DO NOT EDIT!


#ifndef MAP_FILE_MESSAGE_ROADMARK_H
#define MAP_FILE_MESSAGE_ROADMARK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_file
{
template <class ContainerAllocator>
struct RoadMark_
{
  typedef RoadMark_<ContainerAllocator> Type;

  RoadMark_()
    : id(0)
    , aid(0)
    , type(0)
    , linkid(0)  {
    }
  RoadMark_(const ContainerAllocator& _alloc)
    : id(0)
    , aid(0)
    , type(0)
    , linkid(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _aid_type;
  _aid_type aid;

   typedef int32_t _type_type;
  _type_type type;

   typedef int32_t _linkid_type;
  _linkid_type linkid;




  typedef boost::shared_ptr< ::map_file::RoadMark_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_file::RoadMark_<ContainerAllocator> const> ConstPtr;

}; // struct RoadMark_

typedef ::map_file::RoadMark_<std::allocator<void> > RoadMark;

typedef boost::shared_ptr< ::map_file::RoadMark > RoadMarkPtr;
typedef boost::shared_ptr< ::map_file::RoadMark const> RoadMarkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_file::RoadMark_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_file::RoadMark_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_file

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'map_file': ['/home/hj/catkin_ws/src/data/packages/map_file/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_file::RoadMark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_file::RoadMark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::RoadMark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::RoadMark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::RoadMark_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::RoadMark_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_file::RoadMark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18e3d004d39a0c265b34a63968d60155";
  }

  static const char* value(const ::map_file::RoadMark_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18e3d004d39a0c26ULL;
  static const uint64_t static_value2 = 0x5b34a63968d60155ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_file::RoadMark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_file/RoadMark";
  }

  static const char* value(const ::map_file::RoadMark_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_file::RoadMark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
int32 aid\n\
int32 type # Don't use wide character\n\
int32 linkid\n\
";
  }

  static const char* value(const ::map_file::RoadMark_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_file::RoadMark_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.aid);
      stream.next(m.type);
      stream.next(m.linkid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoadMark_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_file::RoadMark_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_file::RoadMark_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "aid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.aid);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "linkid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.linkid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_FILE_MESSAGE_ROADMARK_H
