// Generated by gencpp from file map_file/VectorClass.msg
// DO NOT EDIT!


#ifndef MAP_FILE_MESSAGE_VECTORCLASS_H
#define MAP_FILE_MESSAGE_VECTORCLASS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_file
{
template <class ContainerAllocator>
struct VectorClass_
{
  typedef VectorClass_<ContainerAllocator> Type;

  VectorClass_()
    : vid(0)
    , pid(0)
    , hang(0.0)
    , vang(0.0)  {
    }
  VectorClass_(const ContainerAllocator& _alloc)
    : vid(0)
    , pid(0)
    , hang(0.0)
    , vang(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _vid_type;
  _vid_type vid;

   typedef int32_t _pid_type;
  _pid_type pid;

   typedef double _hang_type;
  _hang_type hang;

   typedef double _vang_type;
  _vang_type vang;




  typedef boost::shared_ptr< ::map_file::VectorClass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_file::VectorClass_<ContainerAllocator> const> ConstPtr;

}; // struct VectorClass_

typedef ::map_file::VectorClass_<std::allocator<void> > VectorClass;

typedef boost::shared_ptr< ::map_file::VectorClass > VectorClassPtr;
typedef boost::shared_ptr< ::map_file::VectorClass const> VectorClassConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_file::VectorClass_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_file::VectorClass_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_file

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'map_file': ['/home/hj/catkin_ws/src/data/packages/map_file/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_file::VectorClass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_file::VectorClass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::VectorClass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::VectorClass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::VectorClass_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::VectorClass_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_file::VectorClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31b12e48aa00ab978560f41960d4e3c5";
  }

  static const char* value(const ::map_file::VectorClass_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31b12e48aa00ab97ULL;
  static const uint64_t static_value2 = 0x8560f41960d4e3c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_file::VectorClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_file/VectorClass";
  }

  static const char* value(const ::map_file::VectorClass_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_file::VectorClass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 vid\n\
int32 pid\n\
float64 hang\n\
float64 vang\n\
";
  }

  static const char* value(const ::map_file::VectorClass_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_file::VectorClass_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vid);
      stream.next(m.pid);
      stream.next(m.hang);
      stream.next(m.vang);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VectorClass_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_file::VectorClass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_file::VectorClass_<ContainerAllocator>& v)
  {
    s << indent << "vid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vid);
    s << indent << "pid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pid);
    s << indent << "hang: ";
    Printer<double>::stream(s, indent + "  ", v.hang);
    s << indent << "vang: ";
    Printer<double>::stream(s, indent + "  ", v.vang);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_FILE_MESSAGE_VECTORCLASS_H
