// Generated by gencpp from file map_file/WhiteLine.msg
// DO NOT EDIT!


#ifndef MAP_FILE_MESSAGE_WHITELINE_H
#define MAP_FILE_MESSAGE_WHITELINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_file
{
template <class ContainerAllocator>
struct WhiteLine_
{
  typedef WhiteLine_<ContainerAllocator> Type;

  WhiteLine_()
    : id(0)
    , lid(0)
    , width(0.0)
    , color(0)
    , type(0)
    , linkid(0)  {
    }
  WhiteLine_(const ContainerAllocator& _alloc)
    : id(0)
    , lid(0)
    , width(0.0)
    , color(0)
    , type(0)
    , linkid(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _lid_type;
  _lid_type lid;

   typedef double _width_type;
  _width_type width;

   typedef int8_t _color_type;
  _color_type color;

   typedef int32_t _type_type;
  _type_type type;

   typedef int32_t _linkid_type;
  _linkid_type linkid;




  typedef boost::shared_ptr< ::map_file::WhiteLine_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_file::WhiteLine_<ContainerAllocator> const> ConstPtr;

}; // struct WhiteLine_

typedef ::map_file::WhiteLine_<std::allocator<void> > WhiteLine;

typedef boost::shared_ptr< ::map_file::WhiteLine > WhiteLinePtr;
typedef boost::shared_ptr< ::map_file::WhiteLine const> WhiteLineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_file::WhiteLine_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_file::WhiteLine_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_file

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'map_file': ['/home/hj/catkin_ws/src/data/packages/map_file/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_file::WhiteLine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_file::WhiteLine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::WhiteLine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_file::WhiteLine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::WhiteLine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_file::WhiteLine_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_file::WhiteLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35e3d11f0af71cc83523b999449b4535";
  }

  static const char* value(const ::map_file::WhiteLine_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35e3d11f0af71cc8ULL;
  static const uint64_t static_value2 = 0x3523b999449b4535ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_file::WhiteLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_file/WhiteLine";
  }

  static const char* value(const ::map_file::WhiteLine_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_file::WhiteLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
int32 lid\n\
float64 width\n\
int8 color\n\
int32 type\n\
int32 linkid\n\
";
  }

  static const char* value(const ::map_file::WhiteLine_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_file::WhiteLine_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.lid);
      stream.next(m.width);
      stream.next(m.color);
      stream.next(m.type);
      stream.next(m.linkid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhiteLine_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_file::WhiteLine_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_file::WhiteLine_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "lid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lid);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "color: ";
    Printer<int8_t>::stream(s, indent + "  ", v.color);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "linkid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.linkid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_FILE_MESSAGE_WHITELINE_H
