// Generated by gencpp from file points_filter/PointsFilterInfo.msg
// DO NOT EDIT!


#ifndef POINTS_FILTER_MESSAGE_POINTSFILTERINFO_H
#define POINTS_FILTER_MESSAGE_POINTSFILTERINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace points_filter
{
template <class ContainerAllocator>
struct PointsFilterInfo_
{
  typedef PointsFilterInfo_<ContainerAllocator> Type;

  PointsFilterInfo_()
    : header()
    , filter_name()
    , original_points_size(0)
    , filtered_points_size(0)
    , original_ring_size(0)
    , filtered_ring_size(0)
    , exe_time(0.0)  {
    }
  PointsFilterInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , filter_name(_alloc)
    , original_points_size(0)
    , filtered_points_size(0)
    , original_ring_size(0)
    , filtered_ring_size(0)
    , exe_time(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filter_name_type;
  _filter_name_type filter_name;

   typedef int32_t _original_points_size_type;
  _original_points_size_type original_points_size;

   typedef int32_t _filtered_points_size_type;
  _filtered_points_size_type filtered_points_size;

   typedef int32_t _original_ring_size_type;
  _original_ring_size_type original_ring_size;

   typedef int32_t _filtered_ring_size_type;
  _filtered_ring_size_type filtered_ring_size;

   typedef float _exe_time_type;
  _exe_time_type exe_time;




  typedef boost::shared_ptr< ::points_filter::PointsFilterInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::points_filter::PointsFilterInfo_<ContainerAllocator> const> ConstPtr;

}; // struct PointsFilterInfo_

typedef ::points_filter::PointsFilterInfo_<std::allocator<void> > PointsFilterInfo;

typedef boost::shared_ptr< ::points_filter::PointsFilterInfo > PointsFilterInfoPtr;
typedef boost::shared_ptr< ::points_filter::PointsFilterInfo const> PointsFilterInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::points_filter::PointsFilterInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::points_filter::PointsFilterInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace points_filter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'points_filter': ['/home/hj/catkin_ws/src/sensing/data_filter/packages/points_filter/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::points_filter::PointsFilterInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::points_filter::PointsFilterInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::points_filter::PointsFilterInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::points_filter::PointsFilterInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::points_filter::PointsFilterInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::points_filter::PointsFilterInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::points_filter::PointsFilterInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7869d7f7f1c1a33d4e8c440ce193e1c";
  }

  static const char* value(const ::points_filter::PointsFilterInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7869d7f7f1c1a33ULL;
  static const uint64_t static_value2 = 0xd4e8c440ce193e1cULL;
};

template<class ContainerAllocator>
struct DataType< ::points_filter::PointsFilterInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "points_filter/PointsFilterInfo";
  }

  static const char* value(const ::points_filter::PointsFilterInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::points_filter::PointsFilterInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string filter_name\n\
int32 original_points_size\n\
int32 filtered_points_size\n\
int32 original_ring_size\n\
int32 filtered_ring_size\n\
float32 exe_time\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::points_filter::PointsFilterInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::points_filter::PointsFilterInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.filter_name);
      stream.next(m.original_points_size);
      stream.next(m.filtered_points_size);
      stream.next(m.original_ring_size);
      stream.next(m.filtered_ring_size);
      stream.next(m.exe_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointsFilterInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::points_filter::PointsFilterInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::points_filter::PointsFilterInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "filter_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filter_name);
    s << indent << "original_points_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.original_points_size);
    s << indent << "filtered_points_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.filtered_points_size);
    s << indent << "original_ring_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.original_ring_size);
    s << indent << "filtered_ring_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.filtered_ring_size);
    s << indent << "exe_time: ";
    Printer<float>::stream(s, indent + "  ", v.exe_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINTS_FILTER_MESSAGE_POINTSFILTERINFO_H
