// Generated by gencpp from file runtime_manager/ConfigLaneRule.msg
// DO NOT EDIT!


#ifndef RUNTIME_MANAGER_MESSAGE_CONFIGLANERULE_H
#define RUNTIME_MANAGER_MESSAGE_CONFIGLANERULE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace runtime_manager
{
template <class ContainerAllocator>
struct ConfigLaneRule_
{
  typedef ConfigLaneRule_<ContainerAllocator> Type;

  ConfigLaneRule_()
    : header()
    , acceleration(0.0)
    , number_of_zeros_ahead(0)
    , number_of_zeros_behind(0)  {
    }
  ConfigLaneRule_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acceleration(0.0)
    , number_of_zeros_ahead(0)
    , number_of_zeros_behind(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef int32_t _number_of_zeros_ahead_type;
  _number_of_zeros_ahead_type number_of_zeros_ahead;

   typedef int32_t _number_of_zeros_behind_type;
  _number_of_zeros_behind_type number_of_zeros_behind;




  typedef boost::shared_ptr< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigLaneRule_

typedef ::runtime_manager::ConfigLaneRule_<std::allocator<void> > ConfigLaneRule;

typedef boost::shared_ptr< ::runtime_manager::ConfigLaneRule > ConfigLaneRulePtr;
typedef boost::shared_ptr< ::runtime_manager::ConfigLaneRule const> ConfigLaneRuleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::runtime_manager::ConfigLaneRule_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace runtime_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'runtime_manager': ['/home/hj/catkin_ws/src/util/packages/runtime_manager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e297624d23dcc2f31641d9b1ac9dd61f";
  }

  static const char* value(const ::runtime_manager::ConfigLaneRule_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe297624d23dcc2f3ULL;
  static const uint64_t static_value2 = 0x1641d9b1ac9dd61fULL;
};

template<class ContainerAllocator>
struct DataType< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "runtime_manager/ConfigLaneRule";
  }

  static const char* value(const ::runtime_manager::ConfigLaneRule_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 acceleration\n\
int32 number_of_zeros_ahead\n\
int32 number_of_zeros_behind\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::runtime_manager::ConfigLaneRule_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acceleration);
      stream.next(m.number_of_zeros_ahead);
      stream.next(m.number_of_zeros_behind);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigLaneRule_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::runtime_manager::ConfigLaneRule_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::runtime_manager::ConfigLaneRule_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "number_of_zeros_ahead: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number_of_zeros_ahead);
    s << indent << "number_of_zeros_behind: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number_of_zeros_behind);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RUNTIME_MANAGER_MESSAGE_CONFIGLANERULE_H
