// Generated by gencpp from file runtime_manager/ConfigNdtMapping.msg
// DO NOT EDIT!


#ifndef RUNTIME_MANAGER_MESSAGE_CONFIGNDTMAPPING_H
#define RUNTIME_MANAGER_MESSAGE_CONFIGNDTMAPPING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace runtime_manager
{
template <class ContainerAllocator>
struct ConfigNdtMapping_
{
  typedef ConfigNdtMapping_<ContainerAllocator> Type;

  ConfigNdtMapping_()
    : header()
    , resolution(0.0)
    , step_size(0.0)
    , trans_eps(0.0)
    , leaf_size(0.0)  {
    }
  ConfigNdtMapping_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , resolution(0.0)
    , step_size(0.0)
    , trans_eps(0.0)
    , leaf_size(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _resolution_type;
  _resolution_type resolution;

   typedef float _step_size_type;
  _step_size_type step_size;

   typedef float _trans_eps_type;
  _trans_eps_type trans_eps;

   typedef float _leaf_size_type;
  _leaf_size_type leaf_size;




  typedef boost::shared_ptr< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigNdtMapping_

typedef ::runtime_manager::ConfigNdtMapping_<std::allocator<void> > ConfigNdtMapping;

typedef boost::shared_ptr< ::runtime_manager::ConfigNdtMapping > ConfigNdtMappingPtr;
typedef boost::shared_ptr< ::runtime_manager::ConfigNdtMapping const> ConfigNdtMappingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace runtime_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'runtime_manager': ['/home/hj/catkin_ws/src/util/packages/runtime_manager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db6ac5faba9084d452d16ad501d6bb99";
  }

  static const char* value(const ::runtime_manager::ConfigNdtMapping_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb6ac5faba9084d4ULL;
  static const uint64_t static_value2 = 0x52d16ad501d6bb99ULL;
};

template<class ContainerAllocator>
struct DataType< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "runtime_manager/ConfigNdtMapping";
  }

  static const char* value(const ::runtime_manager::ConfigNdtMapping_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 resolution\n\
float32 step_size\n\
float32 trans_eps\n\
float32 leaf_size\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::runtime_manager::ConfigNdtMapping_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.resolution);
      stream.next(m.step_size);
      stream.next(m.trans_eps);
      stream.next(m.leaf_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigNdtMapping_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::runtime_manager::ConfigNdtMapping_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::runtime_manager::ConfigNdtMapping_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    s << indent << "step_size: ";
    Printer<float>::stream(s, indent + "  ", v.step_size);
    s << indent << "trans_eps: ";
    Printer<float>::stream(s, indent + "  ", v.trans_eps);
    s << indent << "leaf_size: ";
    Printer<float>::stream(s, indent + "  ", v.leaf_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RUNTIME_MANAGER_MESSAGE_CONFIGNDTMAPPING_H
