// Generated by gencpp from file runtime_manager/ConfigRandomFilter.msg
// DO NOT EDIT!


#ifndef RUNTIME_MANAGER_MESSAGE_CONFIGRANDOMFILTER_H
#define RUNTIME_MANAGER_MESSAGE_CONFIGRANDOMFILTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace runtime_manager
{
template <class ContainerAllocator>
struct ConfigRandomFilter_
{
  typedef ConfigRandomFilter_<ContainerAllocator> Type;

  ConfigRandomFilter_()
    : sample_num(0)  {
    }
  ConfigRandomFilter_(const ContainerAllocator& _alloc)
    : sample_num(0)  {
  (void)_alloc;
    }



   typedef int32_t _sample_num_type;
  _sample_num_type sample_num;




  typedef boost::shared_ptr< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigRandomFilter_

typedef ::runtime_manager::ConfigRandomFilter_<std::allocator<void> > ConfigRandomFilter;

typedef boost::shared_ptr< ::runtime_manager::ConfigRandomFilter > ConfigRandomFilterPtr;
typedef boost::shared_ptr< ::runtime_manager::ConfigRandomFilter const> ConfigRandomFilterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace runtime_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'runtime_manager': ['/home/hj/catkin_ws/src/util/packages/runtime_manager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7a5f13bb56f09ce70b98b9912d3ba96";
  }

  static const char* value(const ::runtime_manager::ConfigRandomFilter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7a5f13bb56f09ceULL;
  static const uint64_t static_value2 = 0x70b98b9912d3ba96ULL;
};

template<class ContainerAllocator>
struct DataType< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "runtime_manager/ConfigRandomFilter";
  }

  static const char* value(const ::runtime_manager::ConfigRandomFilter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sample_num\n\
\n\
";
  }

  static const char* value(const ::runtime_manager::ConfigRandomFilter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sample_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigRandomFilter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::runtime_manager::ConfigRandomFilter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::runtime_manager::ConfigRandomFilter_<ContainerAllocator>& v)
  {
    s << indent << "sample_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sample_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RUNTIME_MANAGER_MESSAGE_CONFIGRANDOMFILTER_H
